# The latest versions are available at https://quiltmc.org/en/usage/latest-versions/
[versions]
minecraft = "1.20.4"
quilt_mappings = "1.20.4+build.3"

quilt_loom = "1.6.5"
quilt_loader = "0.25.0"
quilted_fabric_api = "9.0.0-alpha.8+0.97.0-1.20.4"

spruceui_version = "5.0.3+1.20.2"
modmenu_version = "9.0.0"

minotaur = "2.+"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }

quilted_fabric_api = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api", version.ref = "quilted_fabric_api" }
spruce_ui = { module = "dev.lambdaurora:spruceui", version.ref = "spruceui_version" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu_version" }

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version.ref = "quilt_loom" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
